apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-svc-ingress
  labels:
    name: go-svc-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-svc-service
            port: 
              number: 80
